#define FTYPE_CONTROL 0x00
#define FTYPE_DATA 0x10

#define STYPE_CONTROL_READY_TO_SEND 0x00
#define STYPE_CONTROL_SEND_REQ 0x01
#define STYPE_CONTROL_STOP_REQ 0x02
#define STYPE_CONTROL_EXIT 0x03
#define STYPE_CONTROL_DATA_ACK 0x04
#define STYPE_CONTROL_ERROR 0x05
//#define STYPE_CONTROL_STOP_ACK 0x06

#define STYPE_DATA 0x10
#define STYPE_DATA_GLOBAL_HEADER 0x11

#define EVSE 1
#define EV 2

#define CMD_ERROR 0
#define CMD_DATA_ACK 1
#define CMD_SEND_REQ_ALL 2
#define CMD_SEND_REQ_EV_EVSE 3
#define CMD_STOP_REQ 4
#define CMD_EXIT_REQ 5
#define CMD_ERROR_TX 6
